[tool.poetry]
name = "r_s"
version = "0.1.0"
description = ""
authors = ["Tu Nombre <tu_correo@ejemplo.com>"]
#package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
dagster = "1.9.3"
tensorflow = "^2.12.0"
