version: 2

sources:
  - name: mlops
    description: "machine learning raw tables"
    database: mlops
    schema: source
    tables:
      - name: scores
      - name: movies
        meta:
          dagster:
            asset_key: ["ab_movies"]
      - name: users
        config:
          meta:
            dagster:
              group: marketing
